name: Update devcontainer.json

on:
  schedule:
    - cron: '0 0 1 * *' # Run at midnight on the first day of every month
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Manual run test scenario'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install PyGithub

    - name: Update devcontainer.json
      run: python .github/scripts/update_devcontainer.py

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update devcontainer.json'
        title: 'Update devcontainer.json'
        branch: 'update-devcontainer'
        body: 'This PR updates the components in the devcontainer.json file to their latest versions.'
        labels: 'dependencies, devcontainer'
